name: "Grove Setup"
description: "Shared setup for all Grove CI/CD workflows — checkout, pnpm, Node.js, install, and optional engine/foliage builds"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  build-engine:
    description: "Build the engine package (libs/engine)"
    required: false
    default: "false"
  build-foliage:
    description: "Build the foliage package (libs/foliage)"
    required: false
    default: "false"
  install-filter:
    description: "pnpm install filter (e.g. '--filter=grove-landing'). Empty = full install."
    required: false
    default: ""
  checkout-ref:
    description: "Git ref to checkout (default: current)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-ref == ''

    - name: Checkout (specific ref)
      uses: actions/checkout@v4
      if: inputs.checkout-ref != ''
      with:
        ref: ${{ inputs.checkout-ref }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
        cache-dependency-path: "**/pnpm-lock.yaml"

    - name: Install dependencies
      shell: bash
      env:
        INSTALL_FILTER: ${{ inputs.install-filter }}
      run: |
        if [ -n "$INSTALL_FILTER" ]; then
          pnpm install $INSTALL_FILTER
        else
          pnpm install
        fi

    - name: Build foliage
      if: inputs.build-foliage == 'true'
      shell: bash
      run: pnpm run build
      working-directory: libs/foliage

    - name: Build engine
      if: inputs.build-engine == 'true'
      shell: bash
      run: pnpm run package
      working-directory: libs/engine
