// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "production" | "development";
	MAX_BATCHES: "6" | "2";
	TARGET_RESULTS: "25";
	DRIVER_PROVIDER: "deepseek";
	SWARM_PROVIDER: "deepseek";
	SEARCH_JOB: DurableObjectNamespace<import("./src/index").SearchJobDO>;
	DB: D1Database;
	AI: Ai;
}
